[package]
name = "test"
version = "1.0.0"
authors = []

[addresses]
crime_report = "0f38bcadcc3760f984853fd21675cbd9bbaba0c3cb74ece3574719357b964616"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
